# Generated by Django 4.2.4 on 2026-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='access_code',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
